language: python

sudo: required

services:
  - docker

env:
  - DOCKER_IMG=jackd13/machinelearning:tensorflow14

install:
  - docker pull $DOCKER_IMG

before_script:

script:
  - CODE_COV_ENVS=`bash <(curl -s https://codecov.io/env)`
  - docker run --mount type=bind,source="$(pwd)",target=/home/travisDir $CODE_COV_ENVS $DOCKER_IMG /bin/bash -c "cd /home/travisDir && pytest --cov=TFHelpers && bash <(curl -s https://codecov.io/bash)"

after_success:
